//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreMessaging_NotificationTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoreMessaging_NotificationTypes()
        {
            this.CoreMessaging_Messages = new HashSet<CoreMessaging_Messages>();
            this.CoreMessaging_NotificationTypeActions = new HashSet<CoreMessaging_NotificationTypeActions>();
        }
    
        public int NotificationTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> TTL { get; set; }
        public Nullable<int> DesktopModuleID { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public bool IsTask { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoreMessaging_Messages> CoreMessaging_Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoreMessaging_NotificationTypeActions> CoreMessaging_NotificationTypeActions { get; set; }
        public virtual DesktopModules DesktopModules { get; set; }
    }
}
