//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportImportCheckpoints
    {
        public int CheckpointId { get; set; }
        public int JobId { get; set; }
        public string AssemblyName { get; set; }
        public string Category { get; set; }
        public int Stage { get; set; }
        public string StageData { get; set; }
        public int Progress { get; set; }
        public int TotalItems { get; set; }
        public int ProcessedItems { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<bool> Completed { get; set; }
    
        public virtual ExportImportJobs ExportImportJobs { get; set; }
    }
}
