//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Files()
        {
            this.FileVersions = new HashSet<FileVersions>();
        }
    
        public int FileId { get; set; }
        public Nullable<int> PortalId { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public int Size { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string ContentType { get; set; }
        public int FolderID { get; set; }
        public byte[] Content { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public System.Guid UniqueId { get; set; }
        public System.Guid VersionGuid { get; set; }
        public string SHA1Hash { get; set; }
        public System.DateTime LastModificationTime { get; set; }
        public string Folder { get; set; }
        public string Title { get; set; }
        public System.DateTime StartDate { get; set; }
        public bool EnablePublishPeriod { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int PublishedVersion { get; set; }
        public Nullable<int> ContentItemID { get; set; }
        public bool HasBeenPublished { get; set; }
        public string Description { get; set; }
    
        public virtual ContentItems ContentItems { get; set; }
        public virtual Folders Folders { get; set; }
        public virtual Portals Portals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileVersions> FileVersions { get; set; }
    }
}
