//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_Promotions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hcc_Promotions()
        {
            this.hcc_PromotionTranslations = new HashSet<hcc_PromotionTranslations>();
        }
    
        public long Id { get; set; }
        public long StoreId { get; set; }
        public int Mode { get; set; }
        public System.DateTime LastUpdatedUtc { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDateUtc { get; set; }
        public System.DateTime EndDateUtc { get; set; }
        public bool IsEnabled { get; set; }
        public string QualificationsXml { get; set; }
        public string ActionsXml { get; set; }
        public bool DoNotCombine { get; set; }
        public int SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hcc_PromotionTranslations> hcc_PromotionTranslations { get; set; }
    }
}
