//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_Countries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hcc_Countries()
        {
            this.hcc_CountryTranslations = new HashSet<hcc_CountryTranslations>();
            this.hcc_Regions = new HashSet<hcc_Regions>();
        }
    
        public System.Guid CountryId { get; set; }
        public string CultureCode { get; set; }
        public string SystemName { get; set; }
        public string IsoCode { get; set; }
        public string IsoAlpha3 { get; set; }
        public string IsoNumeric { get; set; }
        public string PostalCodeValidationRegex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hcc_CountryTranslations> hcc_CountryTranslations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hcc_Regions> hcc_Regions { get; set; }
    }
}
