//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_Regions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hcc_Regions()
        {
            this.hcc_RegionTranslations = new HashSet<hcc_RegionTranslations>();
        }
    
        public System.Guid RegionId { get; set; }
        public System.Guid CountryId { get; set; }
        public string Abbreviation { get; set; }
        public string SystemName { get; set; }
    
        public virtual hcc_Countries hcc_Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hcc_RegionTranslations> hcc_RegionTranslations { get; set; }
    }
}
