//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_HtmlTemplates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hcc_HtmlTemplates()
        {
            this.hcc_HtmlTemplateTranslations = new HashSet<hcc_HtmlTemplateTranslations>();
        }
    
        public long Id { get; set; }
        public long StoreId { get; set; }
        public System.DateTime LastUpdatedUtc { get; set; }
        public string DisplayName { get; set; }
        public string FromEmail { get; set; }
        public int TemplateType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hcc_HtmlTemplateTranslations> hcc_HtmlTemplateTranslations { get; set; }
    }
}
