//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_ProductPropertyValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hcc_ProductPropertyValue()
        {
            this.hcc_ProductPropertyValueTranslations = new HashSet<hcc_ProductPropertyValueTranslations>();
        }
    
        public System.Guid ProductBvin { get; set; }
        public long PropertyId { get; set; }
        public string PropertyValue { get; set; }
        public long StoreId { get; set; }
        public long Id { get; set; }
    
        public virtual hcc_Product hcc_Product { get; set; }
        public virtual hcc_ProductProperty hcc_ProductProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hcc_ProductPropertyValueTranslations> hcc_ProductPropertyValueTranslations { get; set; }
    }
}
