//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_UserAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hcc_UserAccounts()
        {
            this.hcc_AuthTokens = new HashSet<hcc_AuthTokens>();
            this.hcc_StoresXUsers = new HashSet<hcc_StoresXUsers>();
        }
    
        public long Id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int statuscode { get; set; }
        public string Salt { get; set; }
        public string ResetKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hcc_AuthTokens> hcc_AuthTokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hcc_StoresXUsers> hcc_StoresXUsers { get; set; }
    }
}
