//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_ShippingMethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hcc_ShippingMethod()
        {
            this.hcc_ShippingMethodTranslations = new HashSet<hcc_ShippingMethodTranslations>();
        }
    
        public System.Guid bvin { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public decimal Adjustment { get; set; }
        public int AdjustmentType { get; set; }
        public string ShippingProviderId { get; set; }
        public long StoreId { get; set; }
        public long ZoneId { get; set; }
        public string Settings { get; set; }
        public int VisibilityMode { get; set; }
        public Nullable<decimal> VisibilityAmount { get; set; }
        public int SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hcc_ShippingMethodTranslations> hcc_ShippingMethodTranslations { get; set; }
    }
}
