//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_SearchObjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hcc_SearchObjects()
        {
            this.hcc_SearchObjectWords = new HashSet<hcc_SearchObjectWords>();
        }
    
        public long Id { get; set; }
        public int ObjectType { get; set; }
        public System.Guid ObjectId { get; set; }
        public string Title { get; set; }
        public long SiteId { get; set; }
        public System.DateTime LastIndexUtc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hcc_SearchObjectWords> hcc_SearchObjectWords { get; set; }
    }
}
