//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_ProductPropertyChoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hcc_ProductPropertyChoice()
        {
            this.hcc_ProductPropertyChoiceTranslations = new HashSet<hcc_ProductPropertyChoiceTranslations>();
        }
    
        public long Id { get; set; }
        public long PropertyId { get; set; }
        public string ChoiceName { get; set; }
        public int SortOrder { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public long StoreId { get; set; }
    
        public virtual hcc_ProductProperty hcc_ProductProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hcc_ProductPropertyChoiceTranslations> hcc_ProductPropertyChoiceTranslations { get; set; }
    }
}
