//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VertikalDataEntities : DbContext
    {
        public VertikalDataEntities()
            : base("name=VertikalDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnonymousUsers> AnonymousUsers { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<Assemblies> Assemblies { get; set; }
        public virtual DbSet<AuthCookies> AuthCookies { get; set; }
        public virtual DbSet<Authentication> Authentication { get; set; }
        public virtual DbSet<CKE_Settings> CKE_Settings { get; set; }
        public virtual DbSet<ContentItems> ContentItems { get; set; }
        public virtual DbSet<ContentItems_MetaData> ContentItems_MetaData { get; set; }
        public virtual DbSet<ContentItems_Tags> ContentItems_Tags { get; set; }
        public virtual DbSet<ContentWorkflowActions> ContentWorkflowActions { get; set; }
        public virtual DbSet<ContentWorkflowLogs> ContentWorkflowLogs { get; set; }
        public virtual DbSet<ContentWorkflows> ContentWorkflows { get; set; }
        public virtual DbSet<ContentWorkflowSources> ContentWorkflowSources { get; set; }
        public virtual DbSet<ContentWorkflowStatePermission> ContentWorkflowStatePermission { get; set; }
        public virtual DbSet<ContentWorkflowStates> ContentWorkflowStates { get; set; }
        public virtual DbSet<ContentTypes> ContentTypes { get; set; }
        public virtual DbSet<CoreMessaging_MessageAttachments> CoreMessaging_MessageAttachments { get; set; }
        public virtual DbSet<CoreMessaging_MessageRecipients> CoreMessaging_MessageRecipients { get; set; }
        public virtual DbSet<CoreMessaging_Messages> CoreMessaging_Messages { get; set; }
        public virtual DbSet<CoreMessaging_NotificationTypeActions> CoreMessaging_NotificationTypeActions { get; set; }
        public virtual DbSet<CoreMessaging_NotificationTypes> CoreMessaging_NotificationTypes { get; set; }
        public virtual DbSet<CoreMessaging_Subscriptions> CoreMessaging_Subscriptions { get; set; }
        public virtual DbSet<CoreMessaging_SubscriptionTypes> CoreMessaging_SubscriptionTypes { get; set; }
        public virtual DbSet<CoreMessaging_UserPreferences> CoreMessaging_UserPreferences { get; set; }
        public virtual DbSet<DesktopModulePermission> DesktopModulePermission { get; set; }
        public virtual DbSet<DesktopModules> DesktopModules { get; set; }
        public virtual DbSet<DNNBCEHelloWorld_Items> DNNBCEHelloWorld_Items { get; set; }
        public virtual DbSet<EventLog> EventLog { get; set; }
        public virtual DbSet<EventLogConfig> EventLogConfig { get; set; }
        public virtual DbSet<EventLogTypes> EventLogTypes { get; set; }
        public virtual DbSet<EventQueue> EventQueue { get; set; }
        public virtual DbSet<ExceptionEvents> ExceptionEvents { get; set; }
        public virtual DbSet<Exceptions> Exceptions { get; set; }
        public virtual DbSet<ExportImportCheckpoints> ExportImportCheckpoints { get; set; }
        public virtual DbSet<ExportImportJobLogs> ExportImportJobLogs { get; set; }
        public virtual DbSet<ExportImportJobs> ExportImportJobs { get; set; }
        public virtual DbSet<ExportImportSettings> ExportImportSettings { get; set; }
        public virtual DbSet<ExtensionUrlProviderConfiguration> ExtensionUrlProviderConfiguration { get; set; }
        public virtual DbSet<ExtensionUrlProviders> ExtensionUrlProviders { get; set; }
        public virtual DbSet<ExtensionUrlProviderSetting> ExtensionUrlProviderSetting { get; set; }
        public virtual DbSet<ExtensionUrlProviderTab> ExtensionUrlProviderTab { get; set; }
        public virtual DbSet<Files> Files { get; set; }
        public virtual DbSet<FileVersions> FileVersions { get; set; }
        public virtual DbSet<FolderMappings> FolderMappings { get; set; }
        public virtual DbSet<FolderMappingsSettings> FolderMappingsSettings { get; set; }
        public virtual DbSet<FolderPermission> FolderPermission { get; set; }
        public virtual DbSet<Folders> Folders { get; set; }
        public virtual DbSet<hcc_Address> hcc_Address { get; set; }
        public virtual DbSet<hcc_Affiliate> hcc_Affiliate { get; set; }
        public virtual DbSet<hcc_AffiliatePayments> hcc_AffiliatePayments { get; set; }
        public virtual DbSet<hcc_AffiliateReferral> hcc_AffiliateReferral { get; set; }
        public virtual DbSet<hcc_AnalyticsEvents> hcc_AnalyticsEvents { get; set; }
        public virtual DbSet<hcc_ApiKeys> hcc_ApiKeys { get; set; }
        public virtual DbSet<hcc_Audit> hcc_Audit { get; set; }
        public virtual DbSet<hcc_AuthTokens> hcc_AuthTokens { get; set; }
        public virtual DbSet<hcc_BundledProducts> hcc_BundledProducts { get; set; }
        public virtual DbSet<hcc_CatalogRoles> hcc_CatalogRoles { get; set; }
        public virtual DbSet<hcc_Category> hcc_Category { get; set; }
        public virtual DbSet<hcc_CategoryTranslations> hcc_CategoryTranslations { get; set; }
        public virtual DbSet<hcc_CategoryXProperty> hcc_CategoryXProperty { get; set; }
        public virtual DbSet<hcc_ContentBlock> hcc_ContentBlock { get; set; }
        public virtual DbSet<hcc_ContentBlockTranslations> hcc_ContentBlockTranslations { get; set; }
        public virtual DbSet<hcc_ContentColumn> hcc_ContentColumn { get; set; }
        public virtual DbSet<hcc_Countries> hcc_Countries { get; set; }
        public virtual DbSet<hcc_CountryTranslations> hcc_CountryTranslations { get; set; }
        public virtual DbSet<hcc_CustomUrl> hcc_CustomUrl { get; set; }
        public virtual DbSet<hcc_Fraud> hcc_Fraud { get; set; }
        public virtual DbSet<hcc_GiftCard> hcc_GiftCard { get; set; }
        public virtual DbSet<hcc_HtmlTemplates> hcc_HtmlTemplates { get; set; }
        public virtual DbSet<hcc_HtmlTemplateTranslations> hcc_HtmlTemplateTranslations { get; set; }
        public virtual DbSet<hcc_LineItem> hcc_LineItem { get; set; }
        public virtual DbSet<hcc_MailingList> hcc_MailingList { get; set; }
        public virtual DbSet<hcc_MailingListMember> hcc_MailingListMember { get; set; }
        public virtual DbSet<hcc_Manufacturer> hcc_Manufacturer { get; set; }
        public virtual DbSet<hcc_MembershipProductType> hcc_MembershipProductType { get; set; }
        public virtual DbSet<hcc_News> hcc_News { get; set; }
        public virtual DbSet<hcc_Order> hcc_Order { get; set; }
        public virtual DbSet<hcc_OrderCoupon> hcc_OrderCoupon { get; set; }
        public virtual DbSet<hcc_OrderNote> hcc_OrderNote { get; set; }
        public virtual DbSet<hcc_OrderPackage> hcc_OrderPackage { get; set; }
        public virtual DbSet<hcc_OrderTransactions> hcc_OrderTransactions { get; set; }
        public virtual DbSet<hcc_PriceGroup> hcc_PriceGroup { get; set; }
        public virtual DbSet<hcc_Product> hcc_Product { get; set; }
        public virtual DbSet<hcc_ProductFile> hcc_ProductFile { get; set; }
        public virtual DbSet<hcc_ProductFileXProduct> hcc_ProductFileXProduct { get; set; }
        public virtual DbSet<hcc_ProductImage> hcc_ProductImage { get; set; }
        public virtual DbSet<hcc_ProductInventory> hcc_ProductInventory { get; set; }
        public virtual DbSet<hcc_ProductOptionItemTranslations> hcc_ProductOptionItemTranslations { get; set; }
        public virtual DbSet<hcc_ProductOptions> hcc_ProductOptions { get; set; }
        public virtual DbSet<hcc_ProductOptionsItems> hcc_ProductOptionsItems { get; set; }
        public virtual DbSet<hcc_ProductOptionTranslations> hcc_ProductOptionTranslations { get; set; }
        public virtual DbSet<hcc_ProductProperty> hcc_ProductProperty { get; set; }
        public virtual DbSet<hcc_ProductPropertyChoice> hcc_ProductPropertyChoice { get; set; }
        public virtual DbSet<hcc_ProductPropertyChoiceTranslations> hcc_ProductPropertyChoiceTranslations { get; set; }
        public virtual DbSet<hcc_ProductPropertyTranslations> hcc_ProductPropertyTranslations { get; set; }
        public virtual DbSet<hcc_ProductPropertyValue> hcc_ProductPropertyValue { get; set; }
        public virtual DbSet<hcc_ProductPropertyValueTranslations> hcc_ProductPropertyValueTranslations { get; set; }
        public virtual DbSet<hcc_ProductRelationships> hcc_ProductRelationships { get; set; }
        public virtual DbSet<hcc_ProductReview> hcc_ProductReview { get; set; }
        public virtual DbSet<hcc_ProductTranslations> hcc_ProductTranslations { get; set; }
        public virtual DbSet<hcc_ProductVolumeDiscounts> hcc_ProductVolumeDiscounts { get; set; }
        public virtual DbSet<hcc_ProductXCategory> hcc_ProductXCategory { get; set; }
        public virtual DbSet<hcc_ProductXOption> hcc_ProductXOption { get; set; }
        public virtual DbSet<hcc_ProductType> hcc_ProductType { get; set; }
        public virtual DbSet<hcc_ProductTypeTranslations> hcc_ProductTypeTranslations { get; set; }
        public virtual DbSet<hcc_ProductTypeXProductProperty> hcc_ProductTypeXProductProperty { get; set; }
        public virtual DbSet<hcc_Promotions> hcc_Promotions { get; set; }
        public virtual DbSet<hcc_PromotionTranslations> hcc_PromotionTranslations { get; set; }
        public virtual DbSet<hcc_QueuedTasks> hcc_QueuedTasks { get; set; }
        public virtual DbSet<hcc_Regions> hcc_Regions { get; set; }
        public virtual DbSet<hcc_RegionTranslations> hcc_RegionTranslations { get; set; }
        public virtual DbSet<hcc_RewardsPoints> hcc_RewardsPoints { get; set; }
        public virtual DbSet<hcc_RMA> hcc_RMA { get; set; }
        public virtual DbSet<hcc_RMAItem> hcc_RMAItem { get; set; }
        public virtual DbSet<hcc_SearchLexicon> hcc_SearchLexicon { get; set; }
        public virtual DbSet<hcc_SearchObjects> hcc_SearchObjects { get; set; }
        public virtual DbSet<hcc_SearchObjectWords> hcc_SearchObjectWords { get; set; }
        public virtual DbSet<hcc_SearchQuery> hcc_SearchQuery { get; set; }
        public virtual DbSet<hcc_ShippingMethod> hcc_ShippingMethod { get; set; }
        public virtual DbSet<hcc_ShippingMethodTranslations> hcc_ShippingMethodTranslations { get; set; }
        public virtual DbSet<hcc_ShippingZones> hcc_ShippingZones { get; set; }
        public virtual DbSet<hcc_StoreDomains> hcc_StoreDomains { get; set; }
        public virtual DbSet<hcc_Stores> hcc_Stores { get; set; }
        public virtual DbSet<hcc_StoreSettings> hcc_StoreSettings { get; set; }
        public virtual DbSet<hcc_StoreSettingsTranslations> hcc_StoreSettingsTranslations { get; set; }
        public virtual DbSet<hcc_StoresXUsers> hcc_StoresXUsers { get; set; }
        public virtual DbSet<hcc_Taxes> hcc_Taxes { get; set; }
        public virtual DbSet<hcc_TaxSchedules> hcc_TaxSchedules { get; set; }
        public virtual DbSet<hcc_User> hcc_User { get; set; }
        public virtual DbSet<hcc_UserAccounts> hcc_UserAccounts { get; set; }
        public virtual DbSet<hcc_UserQuestions> hcc_UserQuestions { get; set; }
        public virtual DbSet<hcc_UserXContact> hcc_UserXContact { get; set; }
        public virtual DbSet<hcc_USGeoData> hcc_USGeoData { get; set; }
        public virtual DbSet<hcc_Variants> hcc_Variants { get; set; }
        public virtual DbSet<hcc_Vendor> hcc_Vendor { get; set; }
        public virtual DbSet<hcc_WishListItems> hcc_WishListItems { get; set; }
        public virtual DbSet<HostSettings> HostSettings { get; set; }
        public virtual DbSet<HtmlText> HtmlText { get; set; }
        public virtual DbSet<HtmlTextLog> HtmlTextLog { get; set; }
        public virtual DbSet<HtmlTextUsers> HtmlTextUsers { get; set; }
        public virtual DbSet<IPFilter> IPFilter { get; set; }
        public virtual DbSet<JavaScriptLibraries> JavaScriptLibraries { get; set; }
        public virtual DbSet<Journal> Journal { get; set; }
        public virtual DbSet<Journal_Access> Journal_Access { get; set; }
        public virtual DbSet<Journal_Comments> Journal_Comments { get; set; }
        public virtual DbSet<Journal_Data> Journal_Data { get; set; }
        public virtual DbSet<Journal_Security> Journal_Security { get; set; }
        public virtual DbSet<Journal_TypeFilters> Journal_TypeFilters { get; set; }
        public virtual DbSet<Journal_Types> Journal_Types { get; set; }
        public virtual DbSet<LanguagePacks> LanguagePacks { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<Lists> Lists { get; set; }
        public virtual DbSet<Messaging_Messages> Messaging_Messages { get; set; }
        public virtual DbSet<MetaData> MetaData { get; set; }
        public virtual DbSet<Mobile_PreviewProfiles> Mobile_PreviewProfiles { get; set; }
        public virtual DbSet<Mobile_RedirectionRules> Mobile_RedirectionRules { get; set; }
        public virtual DbSet<Mobile_Redirections> Mobile_Redirections { get; set; }
        public virtual DbSet<ModuleControls> ModuleControls { get; set; }
        public virtual DbSet<ModuleDefinitions> ModuleDefinitions { get; set; }
        public virtual DbSet<ModulePermission> ModulePermission { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<ModuleSettings> ModuleSettings { get; set; }
        public virtual DbSet<OrderedProducts> OrderedProducts { get; set; }
        public virtual DbSet<OutputCache> OutputCache { get; set; }
        public virtual DbSet<PackageDependencies> PackageDependencies { get; set; }
        public virtual DbSet<Packages> Packages { get; set; }
        public virtual DbSet<PackageTypes> PackageTypes { get; set; }
        public virtual DbSet<PasswordHistory> PasswordHistory { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<PersonaBarExtensions> PersonaBarExtensions { get; set; }
        public virtual DbSet<PersonaBarMenu> PersonaBarMenu { get; set; }
        public virtual DbSet<PersonaBarMenuDefaultPermissions> PersonaBarMenuDefaultPermissions { get; set; }
        public virtual DbSet<PersonaBarMenuPermission> PersonaBarMenuPermission { get; set; }
        public virtual DbSet<PersonaBarPermission> PersonaBarPermission { get; set; }
        public virtual DbSet<PortalAlias> PortalAlias { get; set; }
        public virtual DbSet<PortalDesktopModules> PortalDesktopModules { get; set; }
        public virtual DbSet<PortalGroups> PortalGroups { get; set; }
        public virtual DbSet<PortalLanguages> PortalLanguages { get; set; }
        public virtual DbSet<PortalLocalization> PortalLocalization { get; set; }
        public virtual DbSet<PortalPermission> PortalPermission { get; set; }
        public virtual DbSet<Portals> Portals { get; set; }
        public virtual DbSet<PortalSettings> PortalSettings { get; set; }
        public virtual DbSet<ProductsToOrder> ProductsToOrder { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<ProfilePropertyDefinition> ProfilePropertyDefinition { get; set; }
        public virtual DbSet<RecordvilleLicitModul_Auctions> RecordvilleLicitModul_Auctions { get; set; }
        public virtual DbSet<RecordvilleLicitModul_Items> RecordvilleLicitModul_Items { get; set; }
        public virtual DbSet<RedirectMessages> RedirectMessages { get; set; }
        public virtual DbSet<Relationships> Relationships { get; set; }
        public virtual DbSet<RelationshipTypes> RelationshipTypes { get; set; }
        public virtual DbSet<RoleGroups> RoleGroups { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RoleSettings> RoleSettings { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<ScheduleHistory> ScheduleHistory { get; set; }
        public virtual DbSet<ScheduleItemSettings> ScheduleItemSettings { get; set; }
        public virtual DbSet<SearchCommonWords> SearchCommonWords { get; set; }
        public virtual DbSet<SearchDeletedItems> SearchDeletedItems { get; set; }
        public virtual DbSet<SearchIndexer> SearchIndexer { get; set; }
        public virtual DbSet<SearchStopWords> SearchStopWords { get; set; }
        public virtual DbSet<SearchTypes> SearchTypes { get; set; }
        public virtual DbSet<SiteLog> SiteLog { get; set; }
        public virtual DbSet<SkinControls> SkinControls { get; set; }
        public virtual DbSet<SkinPackages> SkinPackages { get; set; }
        public virtual DbSet<Skins> Skins { get; set; }
        public virtual DbSet<SQLQueries> SQLQueries { get; set; }
        public virtual DbSet<SynonymsGroups> SynonymsGroups { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SystemMessages> SystemMessages { get; set; }
        public virtual DbSet<TabAliasSkins> TabAliasSkins { get; set; }
        public virtual DbSet<TabModules> TabModules { get; set; }
        public virtual DbSet<TabModuleSettings> TabModuleSettings { get; set; }
        public virtual DbSet<TabPermission> TabPermission { get; set; }
        public virtual DbSet<Tabs> Tabs { get; set; }
        public virtual DbSet<TabSettings> TabSettings { get; set; }
        public virtual DbSet<TabUrls> TabUrls { get; set; }
        public virtual DbSet<TabVersionDetails> TabVersionDetails { get; set; }
        public virtual DbSet<TabVersions> TabVersions { get; set; }
        public virtual DbSet<Taxonomy_ScopeTypes> Taxonomy_ScopeTypes { get; set; }
        public virtual DbSet<Taxonomy_Terms> Taxonomy_Terms { get; set; }
        public virtual DbSet<Taxonomy_Vocabularies> Taxonomy_Vocabularies { get; set; }
        public virtual DbSet<Taxonomy_VocabularyTypes> Taxonomy_VocabularyTypes { get; set; }
        public virtual DbSet<UrlLog> UrlLog { get; set; }
        public virtual DbSet<Urls> Urls { get; set; }
        public virtual DbSet<UrlTracking> UrlTracking { get; set; }
        public virtual DbSet<UserAuthentication> UserAuthentication { get; set; }
        public virtual DbSet<UserPortals> UserPortals { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<UserRelationshipPreferences> UserRelationshipPreferences { get; set; }
        public virtual DbSet<UserRelationships> UserRelationships { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersOnline> UsersOnline { get; set; }
        public virtual DbSet<Version> Version { get; set; }
        public virtual DbSet<WebServers> WebServers { get; set; }
        public virtual DbSet<wns_inj_injection> wns_inj_injection { get; set; }
        public virtual DbSet<Workflow> Workflow { get; set; }
        public virtual DbSet<WorkflowStates> WorkflowStates { get; set; }
    }
}
