//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputCache
    {
        public string CacheKey { get; set; }
        public int ItemId { get; set; }
        public string Data { get; set; }
        public System.DateTime Expiration { get; set; }
    }
}
