//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaBarMenuDefaultPermissions
    {
        public int Id { get; set; }
        public int MenuId { get; set; }
        public string RoleNames { get; set; }
    
        public virtual PersonaBarMenu PersonaBarMenu { get; set; }
    }
}
