//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaBarExtensions
    {
        public int ExtensionId { get; set; }
        public string Identifier { get; set; }
        public int MenuId { get; set; }
        public string FolderName { get; set; }
        public string Controller { get; set; }
        public string Container { get; set; }
        public string Path { get; set; }
        public int Order { get; set; }
        public bool Enabled { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
    
        public virtual PersonaBarMenu PersonaBarMenu { get; set; }
    }
}
