//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaBarMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonaBarMenu()
        {
            this.PersonaBarExtensions = new HashSet<PersonaBarExtensions>();
            this.PersonaBarMenu1 = new HashSet<PersonaBarMenu>();
            this.PersonaBarMenuDefaultPermissions = new HashSet<PersonaBarMenuDefaultPermissions>();
            this.PersonaBarMenuPermission = new HashSet<PersonaBarMenuPermission>();
            this.PersonaBarPermission = new HashSet<PersonaBarPermission>();
        }
    
        public int MenuId { get; set; }
        public string Identifier { get; set; }
        public string ModuleName { get; set; }
        public string FolderName { get; set; }
        public string Controller { get; set; }
        public string ResourceKey { get; set; }
        public string Path { get; set; }
        public string Link { get; set; }
        public string CssClass { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int Order { get; set; }
        public bool AllowHost { get; set; }
        public bool Enabled { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public string IconFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaBarExtensions> PersonaBarExtensions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaBarMenu> PersonaBarMenu1 { get; set; }
        public virtual PersonaBarMenu PersonaBarMenu2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaBarMenuDefaultPermissions> PersonaBarMenuDefaultPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaBarMenuPermission> PersonaBarMenuPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaBarPermission> PersonaBarPermission { get; set; }
    }
}
