//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaBarMenuPermission
    {
        public int MenuPermissionId { get; set; }
        public Nullable<int> PortalId { get; set; }
        public int MenuId { get; set; }
        public int PermissionId { get; set; }
        public bool AllowAccess { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
    
        public virtual PersonaBarMenu PersonaBarMenu { get; set; }
        public virtual PersonaBarPermission PersonaBarPermission { get; set; }
        public virtual Portals Portals { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Users Users { get; set; }
    }
}
