//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordvilleLicitModul_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecordvilleLicitModul_Items()
        {
            this.RecordvilleLicitModul_Auctions = new HashSet<RecordvilleLicitModul_Auctions>();
        }
    
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public string ImageUrl { get; set; }
        public int ModuleId { get; set; }
        public Nullable<decimal> HighestPrice { get; set; }
        public Nullable<int> HighestUserId { get; set; }
        public Nullable<System.DateTime> AuctionEndTime { get; set; }
        public Nullable<System.DateTime> AuctionStartTime { get; set; }
        public Nullable<decimal> MinimumBidIncrement { get; set; }
        public decimal StartingPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordvilleLicitModul_Auctions> RecordvilleLicitModul_Auctions { get; set; }
    }
}
