//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordvilleLicitModul_Auctions
    {
        public int AuctionId { get; set; }
        public int ItemId { get; set; }
        public int UserId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime AuctionTime { get; set; }
    
        public virtual RecordvilleLicitModul_Items RecordvilleLicitModul_Items { get; set; }
    }
}
