//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedirectMessages
    {
        public System.Guid MessageId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TabId { get; set; }
        public string MessageText { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
    }
}
