//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabModules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TabModules()
        {
            this.TabModuleSettings = new HashSet<TabModuleSettings>();
        }
    
        public int TabModuleID { get; set; }
        public int TabID { get; set; }
        public int ModuleID { get; set; }
        public string PaneName { get; set; }
        public int ModuleOrder { get; set; }
        public int CacheTime { get; set; }
        public string Alignment { get; set; }
        public string Color { get; set; }
        public string Border { get; set; }
        public string IconFile { get; set; }
        public int Visibility { get; set; }
        public string ContainerSrc { get; set; }
        public bool DisplayTitle { get; set; }
        public bool DisplayPrint { get; set; }
        public bool DisplaySyndicate { get; set; }
        public bool IsWebSlice { get; set; }
        public string WebSliceTitle { get; set; }
        public Nullable<System.DateTime> WebSliceExpiryDate { get; set; }
        public Nullable<int> WebSliceTTL { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public bool IsDeleted { get; set; }
        public string CacheMethod { get; set; }
        public string ModuleTitle { get; set; }
        public string Header { get; set; }
        public string Footer { get; set; }
        public string CultureCode { get; set; }
        public System.Guid UniqueId { get; set; }
        public System.Guid VersionGuid { get; set; }
        public Nullable<System.Guid> DefaultLanguageGuid { get; set; }
        public System.Guid LocalizedVersionGuid { get; set; }
    
        public virtual Modules Modules { get; set; }
        public virtual Tabs Tabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabModuleSettings> TabModuleSettings { get; set; }
    }
}
