//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxonomy_Vocabularies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Taxonomy_Vocabularies()
        {
            this.Taxonomy_Terms = new HashSet<Taxonomy_Terms>();
        }
    
        public int VocabularyID { get; set; }
        public int VocabularyTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Weight { get; set; }
        public Nullable<int> ScopeID { get; set; }
        public int ScopeTypeID { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public bool IsSystem { get; set; }
    
        public virtual Taxonomy_ScopeTypes Taxonomy_ScopeTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Taxonomy_Terms> Taxonomy_Terms { get; set; }
        public virtual Taxonomy_VocabularyTypes Taxonomy_VocabularyTypes { get; set; }
    }
}
