//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLiensApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class wns_inj_injection
    {
        public int injection_id { get; set; }
        public int module_id { get; set; }
        public bool inject_top { get; set; }
        public string inject_name { get; set; }
        public string inject_content { get; set; }
        public int order_shown { get; set; }
        public bool is_enabled { get; set; }
        public string custom_properties { get; set; }
    
        public virtual Modules Modules { get; set; }
    }
}
